GHC-83: MRN Prefix and Demographics
globalhealthcoalition/bahmni-config-ghc pull request #11
Opened 2021-08-12 00:50 UTC by nuhuhmutebi

2021-08-12 16:07 UTC, reagan-meant requested changes

2021-08-12 16:07 UTC, reagan-meant commented on configuration/openmrs/apps/reports/reports.json
> +            "Physical Therapy",
@nuhuhmutebi Are these changes part of this PR?

2021-08-12 16:09 UTC, nuhuhmutebi commented on configuration/openmrs/apps/reports/reports.json
> +            "Physical Therapy",
Yes, they are

2021-08-13 15:18 UTC, reagan-meant approved these changes

2021-08-13 15:19 UTC, merged