GHC-95: Configure patient dashboard
globalhealthcoalition/bahmni-config-ghc pull request #26
Opened 2021-10-07 18:18 UTC by reagan-meant

2021-10-14 12:21 UTC, rbuisson requested changes

2021-10-14 12:21 UTC, rbuisson commented on configuration/openmrs/apps/clinical/dashboard.json
> +            "Profession",
Is this the right concept? In english, shouldn't this be Occupation?

2021-10-14 12:21 UTC, rbuisson commented on configuration/openmrs/obscalculator/BahmniObsValueCalculator.groovy
> + BahmniObservation heightObservation = findByUUID("5090AAAAAAAAAAAAAAAAAAAAAAAAAAAA", observations, null);
Could you specify this as a constant at the top of the file? and substitute any further references by the constant.

2021-10-14 12:21 UTC, rbuisson commented on configuration/openmrs/obscalculator/BahmniObsValueCalculator.groovy
> +            bmiStatusDataObservation = bmiStatusDataObservation ?: createObs("BMI Status Data", null, bahmniEncounterTransaction, obsDatetime) as BahmniObservation
How does that play in other locales?
Should we use UUID here as well?

2021-10-14 12:40 UTC, reagan-meant commented on configuration/openmrs/obscalculator/BahmniObsValueCalculator.groovy
> +            bmiStatusDataObservation = bmiStatusDataObservation ?: createObs("BMI Status Data", null, bahmniEncounterTransaction, obsDatetime) as BahmniObservation
We are using the same name in all locale FSNs.

2021-10-21 10:41 UTC, reagan-meant commented on configuration/openmrs/obscalculator/BahmniObsValueCalculator.groovy
> + BahmniObservation heightObservation = findByUUID("5090AAAAAAAAAAAAAAAAAAAAAAAAAAAA", observations, null);
Done

2021-10-21 10:44 UTC, reagan-meant commented on configuration/openmrs/apps/clinical/dashboard.json
> +            "Profession",
It is fine in English except for the sake of Haiti-Distro alignment we can make it Occupation

2021-11-01 11:39 UTC, merged